'use client';
import Image from 'next/image'; import Link from 'next/link'; import {useEffect,useMemo,useRef,useState} from 'react'; import {ArrowRight,ChevronDown,ChevronLeft,ChevronRight,MapPin,Star,X,Check,Clock,Users} from 'lucide-react'; import {classSessions,faqs,facilities,gallery,memberships,programs,testimonials,trainers,transformations} from '../lib/data'; import {siteConfig} from '../lib/site-config'; import {LeadForm,ContactForm,ClassBookingModal} from './forms/Forms';
export function SectionHead({eyebrow,title,body}:{eyebrow:string;title:string;body?:string}){return <div className="mb-10 max-w-3xl"><p className="eyebrow">{eyebrow}</p><h2 className="display mt-3 text-5xl sm:text-6xl">{title}</h2>{body&&<p className="mt-5 max-w-2xl leading-7 text-neutral-400">{body}</p>}</div>}
export function Hero(){return <section className="relative grid min-h-[760px] items-end overflow-hidden border-b border-white/10"><Image src="https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=2200&q=88" alt="Athlete training in a premium gym" fill priority sizes="100vw" className="object-cover object-center"/><div className="absolute inset-0 bg-gradient-to-t from-black via-black/55 to-black/15"/><div className="container relative z-10 pb-20 pt-36"><div className="max-w-4xl fade"><p className="eyebrow">Mathura's premium training destination</p><h1 className="display mt-4 text-6xl sm:text-8xl lg:text-[7rem]">BUILD YOUR<br/><span className="text-[var(--accent)]">STRONGEST SELF.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-neutral-300 sm:text-lg">Serious equipment. Expert coaching. A focused community. Train with a plan, build confidence and keep getting better.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="btn btn-primary" href="/book-free-trial">START FREE TRIAL <ArrowRight size={16}/></Link><Link className="btn btn-ghost" href="/membership">VIEW MEMBERSHIPS</Link></div><div className="mt-10 grid max-w-3xl grid-cols-2 gap-3 sm:grid-cols-4">{['Certified Trainers','Modern Equipment','Flexible Memberships','7 Days Open'].map(x=><div key={x} className="glass rounded-xl px-4 py-3 text-xs font-bold text-neutral-200">{x}</div>)}</div></div></div></section>}
export function Stats(){return <section className="border-b border-white/10 bg-[#0b0b0b]"><div className="container grid grid-cols-2 divide-x divide-white/10 py-8 md:grid-cols-4">{[['10+','Years Experience'],['2,500+','Members'],['15+','Expert Trainers'],['30+','Weekly Classes']].map(([n,l])=><div key={l} className="px-4 text-center"><b className="text-3xl font-black sm:text-4xl">{n}</b><p className="mt-1 text-xs uppercase tracking-wider text-neutral-500">{l}</p></div>)}</div></section>}
export function Programs(){return <section className="container py-24"><SectionHead eyebrow="Programs & services" title="TRAIN WITH PURPOSE." body="From strength and muscle building to mobility and conditioning, choose a training style that matches your goal."/><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{programs.map(p=><article key={p.id} className="card group overflow-hidden"><div className="relative aspect-[16/10]"><Image src={p.image} alt={p.title} fill sizes="(max-width:768px) 100vw, (max-width:1024px) 50vw, 33vw" className="object-cover transition duration-500 group-hover:scale-105"/></div><div className="p-6"><h3 className="text-xl font-black">{p.title}</h3><p className="mt-2 text-sm leading-6 text-neutral-400">{p.description}</p><Link href={`/programs/${p.id}`} className="mt-5 inline-flex items-center gap-2 text-sm font-black text-[var(--accent)]">Learn More <ArrowRight size={15}/></Link></div></article>)}</div></section>}
export function Memberships(){const [annual,setAnnual]=useState(false);return <section className="bg-[#0b0b0b] py-24"><div className="container"><SectionHead eyebrow="Memberships" title="CHOOSE YOUR LEVEL." body="Simple pricing with clear inclusions. Switch between monthly and annual billing to compare the full cost."/><div className="mb-8 flex justify-center"><div className="rounded-full border border-white/10 bg-black p-1"><button className={`rounded-full px-5 py-2 text-sm font-bold ${!annual?'bg-white text-black':''}`} onClick={()=>setAnnual(false)} aria-pressed={!annual}>Monthly</button><button className={`rounded-full px-5 py-2 text-sm font-bold ${annual?'bg-white text-black':''}`} onClick={()=>setAnnual(true)} aria-pressed={annual}>Annual</button></div></div><div className="grid gap-5 lg:grid-cols-3">{memberships.map(m=>{const savings=m.monthlyPrice*12-m.annualPrice;return <article key={m.id} className={`card relative p-7 ${m.popular?'border-[var(--accent)] shadow-[0_0_50px_rgba(255,77,36,.1)]':''}`}>{m.popular&&<span className="absolute right-5 top-5 rounded-full bg-[var(--accent)] px-3 py-1 text-[10px] font-black uppercase">Most Popular</span>}<h3 className="text-2xl font-black">{m.name}</h3><div className="mt-6 flex items-end gap-2"><span className="text-5xl font-black">₹{annual?m.annualPrice.toLocaleString('en-IN'):m.monthlyPrice.toLocaleString('en-IN')}</span><span className="pb-2 text-sm text-neutral-500">/{annual?'year':'month'}</span></div>{annual&&<p className="mt-2 text-sm text-[var(--accent)]">Save ₹{savings.toLocaleString('en-IN')} per year</p>}<ul className="mt-7 grid gap-3 border-t border-white/10 pt-6 text-sm text-neutral-300">{m.features.map(f=><li key={f} className="flex gap-2"><Check size={17} className="shrink-0 text-[var(--accent)]"/>{f}</li>)}</ul><Link href={`/contact?membership=${m.id}`} className={`btn mt-8 w-full ${m.popular?'btn-primary':'btn-ghost'}`}>ENQUIRE ABOUT {m.name.toUpperCase()}</Link></article>})}</div></div></section>}
export function Trainers(){return <section className="container py-24"><SectionHead eyebrow="Coaching team" title="MEET YOUR COACHES."/><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{trainers.map(t=><article key={t.id} className="card overflow-hidden"><div className="relative aspect-[4/5]"><Image src={t.image} alt={`${t.name}, ${t.specialization}`} fill sizes="(max-width:640px) 50vw, (max-width:1024px) 25vw, 25vw" className="object-cover"/></div><div className="p-5"><h3 className="text-lg font-black">{t.name}</h3><p className="mt-1 text-sm text-[var(--accent)]">{t.specialization}</p><p className="mt-3 text-xs text-neutral-500">{t.experience} • {t.certifications}</p><p className="mt-3 text-sm leading-6 text-neutral-400">{t.bio}</p><Link className="mt-4 inline-flex text-sm font-black" href={`/trainers/${t.id}`}>VIEW PROFILE <ArrowRight size={15} className="ml-2"/></Link></div></article>)}</div></section>}
export function Schedule(){const [day,setDay]=useState('Monday');const [type,setType]=useState('All');const [trainer,setTrainer]=useState('All');const [difficulty,setDifficulty]=useState('All');const [selected,setSelected]=useState<(typeof classSessions)[number]|null>(null);const types=['All',...Array.from(new Set(classSessions.map(x=>x.name)))];const trainersList=['All',...Array.from(new Set(classSessions.map(x=>x.trainer)))];const filtered=useMemo(()=>classSessions.filter(x=>x.day===day&&(type==='All'||x.name===type)&&(trainer==='All'||x.trainer===trainer)&&(difficulty==='All'||x.difficulty===difficulty)),[day,type,trainer,difficulty]);return <section className="container py-16"><SectionHead eyebrow="Weekly timetable" title="FIND YOUR NEXT SESSION." body="Choose a day, then narrow by class type, trainer or difficulty. Every booking is a request until the gym confirms your slot."/><div className="flex gap-2 overflow-x-auto pb-3" role="tablist" aria-label="Days">{['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map(d=><button key={d} role="tab" aria-selected={day===d} onClick={()=>setDay(d)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-bold ${day===d?'bg-[var(--accent)]':'bg-white/5 text-neutral-400'}`}>{d}</button>)}</div><div className="mt-5 grid gap-3 md:grid-cols-3"><select aria-label="Filter by class type" value={type} onChange={e=>setType(e.target.value)} className="field-input"><option value="All">All class types</option>{types.slice(1).map(x=><option key={x}>{x}</option>)}</select><select aria-label="Filter by trainer" value={trainer} onChange={e=>setTrainer(e.target.value)} className="field-input"><option value="All">All trainers</option>{trainersList.slice(1).map(x=><option key={x}>{x}</option>)}</select><select aria-label="Filter by difficulty" value={difficulty} onChange={e=>setDifficulty(e.target.value)} className="field-input"><option>All</option><option>All levels</option><option>Intermediate</option><option>Advanced</option></select></div><div className="mt-6 grid gap-3">{filtered.length?filtered.map(c=><article key={c.id} className="card grid gap-4 p-5 md:grid-cols-[100px_1fr_auto] md:items-center"><div><p className="text-2xl font-black">{c.time}</p><p className="text-xs text-neutral-500">{c.duration}</p></div><div><h3 className="text-lg font-black">{c.name}</h3><div className="mt-1 flex flex-wrap gap-3 text-xs text-neutral-500"><span className="flex items-center gap-1"><Users size={13}/>{c.trainer}</span><span>{c.difficulty}</span><span>{c.spots}</span></div></div><button className="btn btn-primary" onClick={()=>setSelected(c)}>BOOK CLASS</button></article>):<div className="card p-8 text-center text-neutral-500">No sessions match these filters.</div>}</div>{selected&&<ClassBookingModal session={selected} onClose={()=>setSelected(null)}/>}</section>}
export function Gallery(){const [filter,setFilter]=useState('All');const [index,setIndex]=useState<number|null>(null);const categories=['All','Gym','Training','Classes','Trainers','Facilities'];const items=gallery.filter(x=>filter==='All'||x.category===filter);return <section className="container py-24"><SectionHead eyebrow="Inside Ironforge" title="THE SPACE WHERE YOU TRAIN."/><div className="flex flex-wrap gap-2">{categories.map(c=><button key={c} onClick={()=>setFilter(c)} aria-pressed={filter===c} className={`rounded-full px-4 py-2 text-sm font-bold ${filter===c?'bg-[var(--accent)]':'bg-white/5 text-neutral-400'}`}>{c}</button>)}</div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map((item,i)=><button key={item.title+i} className="group relative aspect-[4/3] overflow-hidden rounded-2xl text-left" onClick={()=>setIndex(i)}><Image src={item.image} alt={item.title} fill sizes="(max-width:640px) 100vw, (max-width:1024px) 50vw, 33vw" className="object-cover transition duration-500 group-hover:scale-105"/><span className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/80 to-transparent p-5 text-sm font-black">{item.title}<span className="ml-2 text-[var(--accent)]">{item.category}</span></span></button>)}</div>{index!==null&&<GalleryModal items={items} index={index} setIndex={setIndex}/>}</section>}
function GalleryModal({items,index,setIndex}:{items:typeof gallery;index:number;setIndex:(n:number|null)=>void}) {
  const item=items[index];
  const dialogRef=useRef<HTMLDivElement>(null);

  useEffect(()=>{
    dialogRef.current?.focus();
    const onKeyDown=(event:KeyboardEvent)=>{
      if(event.key==='Escape') setIndex(null);
      if(event.key==='ArrowLeft' && items.length>1) setIndex((index-1+items.length)%items.length);
      if(event.key==='ArrowRight' && items.length>1) setIndex((index+1)%items.length);
    };
    window.addEventListener('keydown',onKeyDown);
    return ()=>window.removeEventListener('keydown',onKeyDown);
  },[index,items.length,setIndex]);

  return <div ref={dialogRef} className="dialog-open fixed inset-0 z-[80] grid place-items-center bg-black/90 p-4" role="dialog" aria-modal="true" aria-label={item.title} tabIndex={-1}
    onMouseDown={e=>{if(e.target===e.currentTarget)setIndex(null)}}>
    <button aria-label="Close image" onClick={()=>setIndex(null)} className="icon-btn absolute right-5 top-5 rounded-full bg-white/10 p-3"><X/></button>
    {items.length>1&&<button aria-label="Previous image" onClick={()=>setIndex((index-1+items.length)%items.length)} className="icon-btn absolute left-3 top-1/2 rounded-full bg-white/10 p-3"><ChevronLeft/></button>}
    <div className="relative h-[80vh] w-full max-w-5xl">
      <Image src={item.image} alt={item.title} fill sizes="90vw" className="object-contain"/>
    </div>
    {items.length>1&&<button aria-label="Next image" onClick={()=>setIndex((index+1)%items.length)} className="icon-btn absolute right-3 top-1/2 rounded-full bg-white/10 p-3"><ChevronRight/></button>}
    <p className="absolute bottom-4 left-1/2 -translate-x-1/2 rounded-full bg-black/70 px-4 py-2 text-xs text-neutral-300">{item.title} · {index+1} / {items.length}</p>
  </div>
}

export function Testimonials(){
  const [i,setI]=useState(0);
  const item=testimonials[i];
  const hasCarousel=testimonials.length>1;
  return <section className="bg-[#0d0d0d] py-24"><div className="container">
    <SectionHead eyebrow="Member stories" title="WHAT MEMBERS SAY"/>
    <div className="card max-w-3xl p-8 sm:p-12">
      <div className="flex gap-1 text-[var(--accent)]">{Array.from({length:item.rating}).map((_,n)=><Star key={n} size={17} fill="currentColor" aria-hidden="true"/>)}</div>
      <p className="mt-7 text-2xl font-bold leading-9 sm:text-3xl">“{item.text}”</p>
      <div className="mt-7"><b>{item.name}</b><p className="text-sm text-neutral-500">Goal: {item.goal}</p></div>
      {hasCarousel&&<div className="mt-8 flex items-center gap-2">
        <button aria-label="Previous testimonial" className="rounded-full border border-white/10 p-2" onClick={()=>setI((i-1+testimonials.length)%testimonials.length)}><ChevronLeft size={16}/></button>
        {testimonials.map((_,n)=><button key={n} aria-label={`Go to testimonial ${n+1}`} aria-current={i===n} onClick={()=>setI(n)} className={`h-2 w-8 rounded-full ${i===n?'bg-[var(--accent)]':'bg-white/10'}`}/>) }
        <button aria-label="Next testimonial" className="rounded-full border border-white/10 p-2" onClick={()=>setI((i+1)%testimonials.length)}><ChevronRight size={16}/></button>
      </div>}
    </div>
  </div></section>
}
export function FAQ(){const [open,setOpen]=useState<number|null>(null);return <section className="container py-24"><SectionHead eyebrow="Questions" title="GOOD TO KNOW BEFORE YOU START."/><div className="max-w-3xl">{faqs.map(([q,a],i)=><div key={q} className="border-b border-white/10"><button className="flex w-full items-center justify-between gap-5 py-5 text-left font-bold" aria-expanded={open===i} aria-controls={`faq-${i}`} onClick={()=>setOpen(open===i?null:i)}><span>{q}</span><ChevronDown className={`transition ${open===i?'rotate-180':''}`}/></button><div id={`faq-${i}`} hidden={open!==i} className="pb-5 text-sm leading-6 text-neutral-400">{a}</div></div>)}</div></section>}
export function Facilities(){return <section className="container py-24"><SectionHead eyebrow="Facilities" title="EVERYTHING YOU NEED TO TRAIN WELL."/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{facilities.map((f,i)=><div key={f} className="card p-5"><p className="text-xs font-black text-[var(--accent)]">0{i+1}</p><h3 className="mt-4 font-black">{f}</h3><p className="mt-2 text-xs leading-5 text-neutral-500">Designed to keep your sessions focused, comfortable and practical.</p></div>)}</div></section>}
export function Transformations(){return <section className="bg-[#0b0b0b] py-24"><div className="container"><SectionHead eyebrow="Member transformations" title="PROGRESS LOOKS DIFFERENT FOR EVERYONE." body="These stories focus on training consistency and measurable habits rather than guaranteed physical outcomes."/><div className="grid gap-5 md:grid-cols-3">{transformations.map(t=><article key={t.name} className="card p-7"><p className="text-xs font-black uppercase tracking-widest text-[var(--accent)]">{t.duration}</p><h3 className="mt-3 text-xl font-black">{t.name}</h3><p className="mt-1 text-sm text-neutral-500">Goal: {t.goal}</p><p className="mt-5 text-sm leading-6 text-neutral-400">{t.story}</p></article>)}</div></div></section>}
export function Location(){return <section className="container py-24"><div className="card grid overflow-hidden lg:grid-cols-2"><div className="p-8 sm:p-12"><p className="eyebrow">Visit us</p><h2 className="display mt-3 text-5xl">COME TRAIN WITH US.</h2><div className="mt-6 grid gap-4 text-sm text-neutral-400"><p className="flex gap-3"><MapPin className="text-[var(--accent)]" size={18}/>{siteConfig.address}, {siteConfig.city}, {siteConfig.state} {siteConfig.postalCode}</p><p className="flex gap-3"><Clock className="text-[var(--accent)]" size={18}/>{siteConfig.openingHours.map(h=><span key={h.days}>{h.days}: {h.hours}</span>)}</p></div><div className="mt-7 flex flex-col gap-3 sm:flex-row"><a className="btn btn-primary" href={siteConfig.googleMapsUrl} target="_blank" rel="noopener noreferrer">GET DIRECTIONS</a><Link className="btn btn-ghost" href="/contact">CONTACT THE GYM</Link></div></div><div className="min-h-[340px] bg-[#151515]"><iframe title="Ironforge Fitness location map" src={siteConfig.mapEmbedUrl} className="h-full min-h-[340px] w-full border-0" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div></div></section>}
